CREATE TRIGGER TRG_FUNCIONARIOS_HIST_SALARIO ON TB_FUNCIONARIO
FOR UPDATE
AS BEGIN
    DECLARE @FUNCIONARIO_ID INT, @SALARIO_ANTIGO MONEY,@SALARIO_NOVO MONEY;

    SELECT @SALARIO_ANTIGO = Salario FROM DELETED;
    SELECT @FUNCIONARIO_ID = FuncionarioId, @SALARIO_NOVO = Salario FROM INSERTED;

    IF @SALARIO_ANTIGO <> @SALARIO_NOVO
    BEGIN
        INSERT INTO TB_HIST_SALARIO
        (FuncionarioId,SALARIO_ANTIGO,SALARIO_NOVO)
        VALUES
        (@FUNCIONARIO_ID,@SALARIO_ANTIGO,@SALARIO_NOVO)
    END
END