-- Função tabular inline

CREATE FUNCTION ListarPedidosCliente(@CLIENTE_ID AS VARCHAR (15))
RETURNS TABLE
AS
RETURN SELECT * FROM TB_PEDIDO WHERE ClienteId = @CLIENTE_ID;

SELECT DISTINCT C1.ClienteId,
        C1.TOTAL_PEDIDOS
        C2.TOTAL_FATURAMENTO
FROM 
(SELECT  ClienteId,
        (SELECT COUNT(*) FROM ListarPedidosCliente(ClienteId)) AS TOTAL_PEDIDOS
FROM TB_PEDIDO) AS C1
INNER JOIN
(SELECT  ClienteId,
        SUM(FaturamentoDetalhePedido(NumeroPedido)) AS TOTAL_FATURAMENTO
FROM TB_PEDIDO
GROUP BY ClienteId) AS C2
ON C1.ClienteId = C2.ClienteId